#!/bin/sh

# Verify correct branch
git checkout develop

# Build new files
stack exec atkv clean
stack exec atkv build

# Temporarily store uncommited changes
git stash -u

# Verify correct branch
git checkout develop

# Get previous files
git fetch --all
git checkout -b master --track origin/master

# Overwrite existing files with new files
yes | cp -a _site/. .

# Commit
git add -A
git commit -m "Publish."

# Push
git push origin master:master

# Restoration
git checkout develop
git branch -D master
git stash pop
